FROM continuumio/miniconda3:23.9.0-0

ENV EXTRACTION_URL=https://github.com/AllenNeuralDynamics/aind-ophys-extraction-suite2p

ARG DEBIAN_FRONTEND=noninteractive

ENV VERSION="0.1.0"
ENV REPO_URL=https://github.com/AllenNeuralDynamics/aind-ophys-oasis-event-detection

RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "vim"]

RUN pip install -U --no-cache-dir \
    h5py==3.9.0 \
    numpy==1.25.1 \
    oasis-deconv==0.2.0 \
    pydantic==2.8.2 \
    seaborn==0.12.2 \
    aind-data-schema==0.22.0